import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'hi';
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    welcome: 'Welcome to Rasoi Setu',
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    role: 'Role',
    retailer: 'Retailer (Vendor)',
    supplier: 'Supplier',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    orders: 'Orders',
    suppliers: 'Suppliers',
    groupOrders: 'Group Orders',
    directOrders: 'Direct Orders',
    browseSuppliers: 'Browse Suppliers',
    comparePrices: 'Compare Prices',
    manageInventory: 'Manage Inventory',
    orderHistory: 'Order History',
    logout: 'Logout',
    submit: 'Submit',
    cancel: 'Cancel',
    confirm: 'Confirm',
    reject: 'Reject',
    pending: 'Pending',
    confirmed: 'Confirmed',
    rejected: 'Rejected',
    price: 'Price',
    stock: 'Stock',
    item: 'Item',
    quantity: 'Quantity',
    total: 'Total',
    storeName: 'Store Name',
    location: 'Location',
    contactInfo: 'Contact Info',
    addToCart: 'Add to Cart',
    placeOrder: 'Place Order',
    joinGroupOrder: 'Join Group Order',
    createGroupOrder: 'Create Group Order',
    targetPrice: 'Target Price',
    minVendors: 'Minimum Vendors',
    deadline: 'Deadline',
    vendorsJoined: 'Vendors Joined',
    itemName: 'Item Name',
    pricePerUnit: 'Price per Unit',
    availableStock: 'Available Stock',
    addItem: 'Add Item',
    updateItem: 'Update Item',
    deleteItem: 'Delete Item',
    searchItems: 'Search Items',
    filter: 'Filter',
    sort: 'Sort',
    lowToHigh: 'Low to High',
    highToLow: 'High to Low',
    downloadReceipt: 'Download Receipt',
    orderDate: 'Order Date',
    orderStatus: 'Order Status',
    totalAmount: 'Total Amount',
    selectRole: 'Select your role',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signInHere: 'Sign in here',
    signUpHere: 'Sign up here',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    profileUpdated: 'Profile updated successfully',
    orderPlaced: 'Order placed successfully',
    orderConfirmed: 'Order confirmed',
    orderRejected: 'Order rejected',
    itemAdded: 'Item added successfully',
    itemUpdated: 'Item updated successfully',
    itemDeleted: 'Item deleted successfully',
    groupOrderCreated: 'Group order created successfully',
    groupOrderJoined: 'Joined group order successfully',
    invalidCredentials: 'Invalid email or password',
    emailAlreadyExists: 'Email already exists',
    passwordTooWeak: 'Password should be at least 6 characters',
    fillAllFields: 'Please fill all required fields',
    noItemsFound: 'No items found',
    noOrdersFound: 'No orders found',
    noSuppliersFound: 'No suppliers found',
    currentOrders: 'Current Orders',
    pastOrders: 'Past Orders',
    activeGroupOrders: 'Active Group Orders',
    expiredGroupOrders: 'Expired Group Orders',
    profile: 'Profile',
    settings: 'Settings',
    language: 'Language',
    notifications: 'Notifications',
    help: 'Help',
    about: 'About',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    contact: 'Contact',
    version: 'Version',
    lastUpdated: 'Last Updated',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    totalItems: 'Total Items',
    pendingDeliveries: 'Pending Deliveries',
    completedToday: 'Completed Today',
    online: 'Online',
    offline: 'Offline',
    retry: 'Retry',
    refresh: 'Refresh',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    remove: 'Remove',
    update: 'Update',
    create: 'Create',
    view: 'View',
    hide: 'Hide',
    show: 'Show',
    search: 'Search',
    clear: 'Clear',
    all: 'All',
    none: 'None',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    close: 'Close',
    open: 'Open',
    new: 'New',
    old: 'Old',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    lastWeek: 'Last Week',
    lastMonth: 'Last Month',
    lastYear: 'Last Year',
  },
  hi: {
    welcome: 'रसोई सेतु में आपका स्वागत है',
    login: 'लॉगिन',
    signup: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    role: 'भूमिका',
    retailer: 'रिटेलर (विक्रेता)',
    supplier: 'आपूर्तिकर्ता',
    dashboard: 'डैशबोर्ड',
    inventory: 'इन्वेंटरी',
    orders: 'ऑर्डर',
    suppliers: 'आपूर्तिकर्ता',
    groupOrders: 'समूह ऑर्डर',
    directOrders: 'प्रत्यक्ष ऑर्डर',
    browseSuppliers: 'आपूर्तिकर्ता ब्राउज़ करें',
    comparePrices: 'कीमतों की तुलना करें',
    manageInventory: 'इन्वेंटरी प्रबंधित करें',
    orderHistory: 'ऑर्डर इतिहास',
    logout: 'लॉगआउट',
    submit: 'सबमिट',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    reject: 'अस्वीकार करें',
    pending: 'लंबित',
    confirmed: 'पुष्ट',
    rejected: 'अस्वीकृत',
    price: 'कीमत',
    stock: 'स्टॉक',
    item: 'वस्तु',
    quantity: 'मात्रा',
    total: 'कुल',
    storeName: 'दुकान का नाम',
    location: 'स्थान',
    contactInfo: 'संपर्क जानकारी',
    addToCart: 'कार्ट में जोड़ें',
    placeOrder: 'ऑर्डर दें',
    joinGroupOrder: 'समूह ऑर्डर में शामिल हों',
    createGroupOrder: 'समूह ऑर्डर बनाएं',
    targetPrice: 'लक्ष्य कीमत',
    minVendors: 'न्यूनतम विक्रेता',
    deadline: 'समय सीमा',
    vendorsJoined: 'शामिल विक्रेता',
    itemName: 'वस्तु का नाम',
    pricePerUnit: 'प्रति यूनिट कीमत',
    availableStock: 'उपलब्ध स्टॉक',
    addItem: 'वस्तु जोड़ें',
    updateItem: 'वस्तु अपडेट करें',
    deleteItem: 'वस्तु हटाएं',
    searchItems: 'वस्तुएं खोजें',
    filter: 'फिल्टर',
    sort: 'क्रमबद्ध करें',
    lowToHigh: 'कम से ज्यादा',
    highToLow: 'ज्यादा से कम',
    downloadReceipt: 'रसीद डाउनलोड करें',
    orderDate: 'ऑर्डर की तारीख',
    orderStatus: 'ऑर्डर स्थिति',
    totalAmount: 'कुल राशि',
    selectRole: 'अपनी भूमिका चुनें',
    alreadyHaveAccount: 'पहले से खाता है?',
    dontHaveAccount: 'खाता नहीं है?',
    signInHere: 'यहाँ साइन इन करें',
    signUpHere: 'यहाँ साइन अप करें',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    profileUpdated: 'प्रोफाइल सफलतापूर्वक अपडेट हुई',
    orderPlaced: 'ऑर्डर सफलतापूर्वक दिया गया',
    orderConfirmed: 'ऑर्डर पुष्ट हुआ',
    orderRejected: 'ऑर्डर अस्वीकृत',
    itemAdded: 'वस्तु सफलतापूर्वक जोड़ी गई',
    itemUpdated: 'वस्तु सफलतापूर्वक अपडेट हुई',
    itemDeleted: 'वस्तु सफलतापूर्वक हटाई गई',
    groupOrderCreated: 'समूह ऑर्डर सफलतापूर्वक बनाया गया',
    groupOrderJoined: 'समूह ऑर्डर में सफलतापूर्वक शामिल हुए',
    invalidCredentials: 'गलत ईमेल या पासवर्ड',
    emailAlreadyExists: 'ईमेल पहले से मौजूद है',
    passwordTooWeak: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    fillAllFields: 'कृपया सभी आवश्यक फील्ड भरें',
    noItemsFound: 'कोई वस्तु नहीं मिली',
    noOrdersFound: 'कोई ऑर्डर नहीं मिला',
    noSuppliersFound: 'कोई आपूर्तिकर्ता नहीं मिला',
    currentOrders: 'वर्तमान ऑर्डर',
    pastOrders: 'पुराने ऑर्डर',
    activeGroupOrders: 'सक्रिय समूह ऑर्डर',
    expiredGroupOrders: 'समाप्त समूह ऑर्डर',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    help: 'सहायता',
    about: 'के बारे में',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    contact: 'संपर्क',
    version: 'संस्करण',
    lastUpdated: 'अंतिम अपडेट',
    getStarted: 'शुरू करें',
    learnMore: 'और जानें',
    totalItems: 'कुल वस्तुएं',
    pendingDeliveries: 'लंबित डिलीवरी',
    completedToday: 'आज पूर्ण',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    retry: 'पुनः प्रयास',
    refresh: 'रीफ्रेश',
    back: 'वापस',
    next: 'अगला',
    previous: 'पिछला',
    save: 'सेव',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    add: 'जोड़ें',
    remove: 'हटाएं',
    update: 'अपडेट',
    create: 'बनाएं',
    view: 'देखें',
    hide: 'छुपाएं',
    show: 'दिखाएं',
    search: 'खोजें',
    clear: 'साफ करें',
    all: 'सभी',
    none: 'कोई नहीं',
    yes: 'हाँ',
    no: 'नहीं',
    ok: 'ठीक है',
    close: 'बंद करें',
    open: 'खोलें',
    new: 'नया',
    old: 'पुराना',
    today: 'आज',
    yesterday: 'कल',
    thisWeek: 'इस सप्ताह',
    thisMonth: 'इस महीने',
    thisYear: 'इस साल',
    lastWeek: 'पिछले सप्ताह',
    lastMonth: 'पिछले महीने',
    lastYear: 'पिछले साल',
  },
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'hi'>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('rasoi-setu-language') as 'en' | 'hi';
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'hi' : 'en';
    setLanguage(newLanguage);
    localStorage.setItem('rasoi-setu-language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  const value = {
    language,
    toggleLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};